### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by futhrevo**
Additional instructions for running on actual device to avoid ECONNREFUSED error

### CODE REVIEW

**Comment by futhrevo** [comment]
Signed CLA

Thanks
Rakesh

**Comment by loosebazooka** [comment]
Thanks for this contribution, but I think it needs to be moved to another section between 2.1 and 2.2 "Testing your app on a device" or something. It also needs to be updated across all relevant Readmes for this repository.

**Comment by futhrevo** [comment]
Do I need to create new pull request or it will be taken care of?

**Comment by loosebazooka** [comment]
I can take care of it. Thanks.

**Pull request closed without merging**
